# -*- coding: utf-8 -*-
"""implementetion that uses DESCRYPTO .py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syoNsnUhYVEfhVoaB7PFp_3PFmMB_D9_
"""

!pip install pyDes

from pyDes import *
message = "0123456781234567"
key = "DESCRYPI"
iv = bytes([0]*8)
k = des(key,CBC,iv,pad=None,padmode=PAD_PKCS5)

cipher = k.encrypt(message)
print("len of cipher text:",len(cipher))
print("Encrypted:", cipher[0:8])
print("Encrypted:", cipher[8:16])
print("Encrypted:", cipher[16:])
message = k.decrypt(cipher)
print("Decrypted",message)

